apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://trinodb.github.io/charts
      chart: trino
      targetRevision: 1.39.1
      helm:
        valueFiles:
          - $values/trino-values.yaml
    - repoURL: https://github.com/AnkushChandra/trino-aws.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
